import type { APIRoute } from 'astro'
import { Webhook } from 'svix'

import { getSupabaseServiceRole, isSupabaseConfigured } from '#libs/supabase-native'
import { logger } from '#utils/logger'

const webhookSecret = import.meta.env.CLERK_WEBHOOK_SECRET

export const POST: APIRoute = async ({ request, locals }) => {
  // Generated by Copilot: Use correlation ID from middleware for distributed tracing
  const correlationId = locals.correlationId || logger.createCorrelationId()
  const ctx = logger.apiRequest('/api/webhooks/clerk', 'POST', undefined, correlationId)

  try {
    await logger.debug('Clerk webhook received', { ...ctx })

    if (!webhookSecret) {
      await logger.error('Clerk webhook secret not configured', { ...ctx })
      await logger.flush()
      return new Response('Webhook secret not configured', { status: 500 })
    }

    // Get webhook headers
    const svixId = request.headers.get('svix-id')
    const svixTimestamp = request.headers.get('svix-timestamp')
    const svixSignature = request.headers.get('svix-signature')

    if (!svixId || !svixTimestamp || !svixSignature) {
      await logger.apiComplete(ctx, 400)
      await logger.flush()
      return new Response('Missing webhook headers', { status: 400 })
    }

    // Verify webhook signature
    const payload = await request.text()
    const wh = new Webhook(webhookSecret)

    interface WebhookEvent {
      type: string
      data: {
        id: string
        email_addresses?: Array<{ id: string; email_address: string }>
        primary_email_address_id?: string
        username?: string
        first_name?: string
        last_name?: string
        image_url?: string
        public_metadata?: Record<string, unknown>
        last_sign_in_at?: number
        created_at?: number
        user_id?: string
        // Organization membership fields
        organization?: {
          id: string
          name: string
          slug: string
        }
        public_user_data?: {
          user_id: string
          first_name?: string
          last_name?: string
        }
        role?: string
      }
    }

    let evt: WebhookEvent
    try {
      evt = wh.verify(payload, {
        'svix-id': svixId,
        'svix-timestamp': svixTimestamp,
        'svix-signature': svixSignature,
      }) as WebhookEvent
    } catch (err) {
      await logger.error('Clerk webhook verification failed', {
        ...ctx,
        error: err instanceof Error ? err.message : 'Unknown error',
      })
      await logger.apiComplete(ctx, 400)
      await logger.flush()
      return new Response('Invalid signature', { status: 400 })
    }

    // Check if Supabase is configured
    if (!isSupabaseConfigured()) {
      await logger.warn('Supabase not configured - skipping user sync', { ...ctx })
      await logger.apiComplete(ctx, 200)
      await logger.flush()
      return new Response('Webhook received but Supabase not configured', { status: 200 })
    }

    // Use service role client for webhook operations
    const supabase = getSupabaseServiceRole()

    if (!supabase) {
      // Generated by Copilot: Replaced console.error with structured logger
      await logger.error('Failed to get Supabase service role client', { ...ctx })
      await logger.apiComplete(ctx, 500)
      await logger.flush()
      return new Response('Supabase service role not available', { status: 500 })
    }

    // Handle different event types
    switch (evt.type) {
      case 'user.created': {
        const {
          id,
          email_addresses,
          username,
          first_name,
          last_name,
          image_url,
          public_metadata,
          last_sign_in_at,
        } = evt.data

        const primaryEmail = email_addresses?.find(
          email => email.id === evt.data.primary_email_address_id
        )

        // Validate that we have at least one valid email address
        const validEmail =
          primaryEmail?.email_address ||
          (email_addresses && email_addresses.length > 0 && email_addresses[0]?.email_address)

        if (!validEmail) {
          logger.error('User sync failed - no valid email address', { userId: id })
          return new Response(
            JSON.stringify({
              error: 'No valid email address found',
              message: 'User sync requires at least one email address',
            }),
            {
              status: 400,
              headers: { 'Content-Type': 'application/json' },
            }
          )
        }

        // Extract role from public metadata, default to 'member'
        const role = (public_metadata?.role as string) || 'member'

        const userData = {
          clerk_id: id,
          email: validEmail,
          username,
          full_name: `${first_name || ''} ${last_name || ''}`.trim() || null,
          avatar_url: image_url,
          role, // User-level role from Clerk
          app_metadata: public_metadata || {},
          last_sign_in_at: last_sign_in_at ? new Date(last_sign_in_at).toISOString() : null,
        }

        const { data: user, error: userError } = await supabase
          .from('users')
          .upsert(userData, {
            onConflict: 'clerk_id',
            ignoreDuplicates: false,
          })
          .select()
          .single()

        if (userError) {
          // Check for duplicate email constraint violation (PostgreSQL error code 23505)
          // This should rarely occur as Clerk prevents duplicates at auth layer
          // Defense-in-depth protection via database constraint idx_users_email_unique
          if (userError.code === '23505' && userError.message?.includes('idx_users_email_unique')) {
            logger.error('Duplicate email detected during user creation', {
              userId: id,
              email: validEmail,
              clerkId: id,
              errorCode: userError.code,
            })
            await logger.flush()
            return new Response(
              JSON.stringify({
                error: 'Email already exists',
                message: 'This email address is already registered with another account.',
              }),
              { status: 409, headers: { 'Content-Type': 'application/json' } }
            )
          }

          // Re-throw other database errors
          logger.error('Failed to sync user', { userId: id, error: userError.message })
          return new Response(`Failed to sync user: ${userError.message}`, { status: 500 })
        }

        // Create default preferences for new users
        if (user) {
          const { error: prefsError } = await supabase
            .from('user_preferences')
            .insert({
              user_id: user.id,
            })
            .onConflict('user_id')
            .ignoreDuplicates()

          if (prefsError) {
            logger.warn('Failed to create default preferences', {
              userId: id,
              error: prefsError.message,
            })
          }
        }

        logger.info('User created and synced', { userId: id, email: validEmail })
        break
      }

      case 'user.updated': {
        const {
          id,
          email_addresses,
          username,
          first_name,
          last_name,
          image_url,
          public_metadata,
          last_sign_in_at,
        } = evt.data

        const primaryEmail = email_addresses?.find(
          email => email.id === evt.data.primary_email_address_id
        )

        const validEmail =
          primaryEmail?.email_address ||
          (email_addresses && email_addresses.length > 0 && email_addresses[0]?.email_address)

        // Extract role from public metadata, default to 'member'
        const role = (public_metadata?.role as string) || 'member'

        const userData = {
          email: validEmail,
          username,
          full_name: `${first_name || ''} ${last_name || ''}`.trim() || null,
          avatar_url: image_url,
          role, // User-level role from Clerk
          app_metadata: public_metadata || {},
          last_sign_in_at: last_sign_in_at ? new Date(last_sign_in_at).toISOString() : null,
        }

        const { error } = await supabase.from('users').update(userData).eq('clerk_id', id)

        if (error) {
          // Check for duplicate email constraint violation (PostgreSQL error code 23505)
          // This should rarely occur as Clerk prevents duplicates at auth layer
          // Defense-in-depth protection via database constraint idx_users_email_unique
          if (error.code === '23505' && error.message?.includes('idx_users_email_unique')) {
            logger.error('Duplicate email detected during user update', {
              userId: id,
              email: validEmail,
              clerkId: id,
              errorCode: error.code,
            })
            await logger.flush()
            return new Response(
              JSON.stringify({
                error: 'Email already exists',
                message:
                  'Cannot update user: This email address is already registered with another account.',
              }),
              { status: 409, headers: { 'Content-Type': 'application/json' } }
            )
          }

          // Re-throw other database errors
          logger.error('Failed to update user', { userId: id, error: error.message })
          return new Response(`Failed to update user: ${error.message}`, { status: 500 })
        }

        logger.info('User updated', { userId: id })
        break
      }

      case 'user.deleted': {
        // Soft delete - anonymize user data
        const { error } = await supabase
          .from('users')
          .update({
            email: null,
            username: `deleted_user_${evt.data.id}`,
            full_name: 'Deleted User',
            avatar_url: null,
            app_metadata: {},
          })
          .eq('clerk_id', evt.data.id)

        if (error) {
          logger.error('Failed to delete user', { userId: evt.data.id, error: error.message })
          return new Response(`Failed to delete user: ${error.message}`, { status: 500 })
        }

        logger.info('User deleted and anonymized', { userId: evt.data.id })
        break
      }

      case 'organizationMembership.created': {
        const { organization, public_user_data, role } = evt.data

        if (!organization || !public_user_data) {
          logger.warn('Organization membership creation missing required data')
          break
        }

        // Get user ID from clerk_id
        const { data: user } = await supabase
          .from('users')
          .select('id')
          .eq('clerk_id', public_user_data.user_id)
          .single()

        if (!user) {
          logger.warn('User not found for organization membership', {
            userId: public_user_data.user_id,
          })
          break
        }

        const { error } = await supabase.from('organization_memberships').insert({
          user_id: user.id,
          clerk_org_id: organization.id,
          clerk_org_role: role || 'org:member',
          org_name: organization.name,
          org_slug: organization.slug,
        })

        if (error) {
          logger.error('Failed to create organization membership', {
            userId: public_user_data.user_id,
            orgId: organization.id,
            error: error.message,
          })
          return new Response(`Failed to create organization membership: ${error.message}`, {
            status: 500,
          })
        }

        logger.info('Organization membership created', {
          userId: public_user_data.user_id,
          orgId: organization.id,
          role: role,
        })
        break
      }

      case 'organizationMembership.updated': {
        const { organization, public_user_data, role } = evt.data

        if (!organization || !public_user_data) {
          logger.warn('Organization membership update missing required data')
          break
        }

        // Get user ID from clerk_id
        const { data: user } = await supabase
          .from('users')
          .select('id')
          .eq('clerk_id', public_user_data.user_id)
          .single()

        if (!user) {
          logger.warn('User not found for organization membership update', {
            userId: public_user_data.user_id,
          })
          break
        }

        const { error } = await supabase
          .from('organization_memberships')
          .update({
            clerk_org_role: role || 'org:member',
            org_name: organization.name,
            org_slug: organization.slug,
          })
          .eq('user_id', user.id)
          .eq('clerk_org_id', organization.id)

        if (error) {
          logger.error('Failed to update organization membership', {
            userId: public_user_data.user_id,
            orgId: organization.id,
            error: error.message,
          })
          return new Response(`Failed to update organization membership: ${error.message}`, {
            status: 500,
          })
        }

        logger.info('Organization membership updated', {
          userId: public_user_data.user_id,
          orgId: organization.id,
          role: role,
        })
        break
      }

      case 'organizationMembership.deleted': {
        const { organization, public_user_data } = evt.data

        if (!organization || !public_user_data) {
          logger.warn('Organization membership deletion missing required data')
          break
        }

        // Get user ID from clerk_id
        const { data: user } = await supabase
          .from('users')
          .select('id')
          .eq('clerk_id', public_user_data.user_id)
          .single()

        if (!user) {
          logger.warn('User not found for organization membership deletion', {
            userId: public_user_data.user_id,
          })
          break
        }

        const { error } = await supabase
          .from('organization_memberships')
          .delete()
          .eq('user_id', user.id)
          .eq('clerk_org_id', organization.id)

        if (error) {
          logger.error('Failed to delete organization membership', {
            userId: public_user_data.user_id,
            orgId: organization.id,
            error: error.message,
          })
          return new Response(`Failed to delete organization membership: ${error.message}`, {
            status: 500,
          })
        }

        logger.info('Organization membership deleted', {
          userId: public_user_data.user_id,
          orgId: organization.id,
        })
        break
      }

      case 'session.created': {
        // Update last sign in time
        if (!evt.data.user_id || !evt.data.created_at) {
          break
        }

        // Log user login event to Axiom for analytics and monitoring
        const loginTimestamp = new Date(evt.data.created_at).toISOString()
        await logger.info('User login successful', {
          userId: evt.data.user_id,
          loginTimestamp,
          correlationId: ctx.correlationId,
          source: 'clerk-webhook',
          eventType: 'session.created',
        })

        const { error } = await supabase
          .from('users')
          .update({
            last_sign_in_at: loginTimestamp,
          })
          .eq('clerk_id', evt.data.user_id)

        if (error) {
          logger.warn('Failed to update last sign in', {
            userId: evt.data.user_id,
            error: error.message,
            correlationId: ctx.correlationId,
          })
        } else {
          logger.debug('Last sign in timestamp updated successfully', {
            userId: evt.data.user_id,
            correlationId: ctx.correlationId,
          })
        }
        break
      }

      default:
        await logger.debug('Unhandled webhook event type', { eventType: evt.type, ...ctx })
    }

    // Generated by Copilot: Track request completion and flush logs
    await logger.apiComplete(ctx, 200)
    await logger.flush()
    return new Response('Webhook processed', { status: 200 })
  } catch (error) {
    // Generated by Copilot: Catch any unhandled errors
    await logger.error('Clerk webhook processing failed', {
      ...ctx,
      error: error instanceof Error ? error.message : 'Unknown error',
    })
    await logger.flush()
    return new Response('Internal server error', { status: 500 })
  }
}
