/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file was generated by scripts/setup-roles.ts
 * Source: config/roles.config.ts
 * Generated: 2025-11-21T21:54:35.452Z
 *
 * To modify roles, edit config/roles.config.ts and run:
 *   npm run setup:roles
 *
 * @module types/generated-roles
 */

/**
 * User role type
 *
 * Represents all available user roles in the application.
 * This type is generated from the role configuration.
 */
export type UserRole = 'member' | 'admin' | 'super_admin'

/**
 * Array of all valid user roles
 *
 * Use this for runtime validation and iteration.
 */
export const USER_ROLES: UserRole[] = ['member', 'admin', 'super_admin'] as const

/**
 * Role hierarchy levels
 *
 * Higher numbers indicate more privileges.
 * Used for hierarchical role checking where higher-level roles
 * can access resources restricted to lower-level roles.
 */
export const ROLE_HIERARCHY: Record<UserRole, number> = {
  member: 1,
  admin: 5,
  super_admin: 10,
} as const

/**
 * Human-readable role labels
 *
 * Maps role identifiers to display-friendly names for UI rendering.
 */
export const ROLE_LABELS: Record<UserRole, string> = {
  member: 'Member',
  admin: 'Administrator',
  super_admin: 'Super Administrator',
} as const

/**
 * Role color configuration
 *
 * Maps role identifiers to color schemes for UI badges and indicators.
 * Colors are automatically generated based on role hierarchy with WCAG AA
 * compliant contrast ratios (minimum 4.5:1).
 *
 * Color scheme:
 * - Low privilege roles (levels 1-3): Blue tones
 * - Mid privilege roles (levels 4-7): Purple tones
 * - High privilege roles (levels 8-10): Amber tones
 */
export const ROLE_COLORS: Record<
  UserRole,
  {
    label: string
    bgColor: string
    textColor: string
    description: string
  }
> = {
  member: {
    label: 'Member',
    bgColor: '#dbeafe',
    textColor: '#1e40af',
    description: 'Standard user with basic permissions',
  },
  admin: {
    label: 'Administrator',
    bgColor: '#e9d5ff',
    textColor: '#6b21a8',
    description: 'Elevated permissions for administrative tasks',
  },
  super_admin: {
    label: 'Super Administrator',
    bgColor: '#fef3c7',
    textColor: '#92400e',
    description: 'Full administrative access and system control',
  },
} as const
