// Astro types are automatically included through astro/client
/// <reference types="astro/client" />
/// <reference types="@clerk/astro/client" />

declare namespace App {
  interface Locals {
    // Custom properties added to the Clerk Locals interface
    correlationId?: string // Generated by Copilot: Unique ID for distributed request tracing
    csrfToken?: string
    userId?: string | null
    userRole?: string // User-level role (application-wide): 'member' | 'admin' | 'super_admin'
    orgRole?: string | null // Organization-specific role: 'org:admin' | 'org:member' | null
    orgId?: string | null // Clerk organization ID
    clerkToken?: string | null
  }
}

interface ImportMetaEnv {
  readonly PWA_ENABLED: string
  readonly ORGANIZATION_ID: string
  readonly PUBLIC_SUPABASE_URL: string
  readonly PUBLIC_SUPABASE_ANON_KEY: string
  readonly AXIOM_TOKEN?: string
  readonly AXIOM_DATASET?: string
  readonly AXIOM_ORG_ID?: string
}
