// Generated by Copilot: Unit tests for logger with Axiom integration
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { logger, createLogger } from '../../src/utils/logger'

describe('Logger with Axiom Integration', () => {
  // Save original console methods
  const originalConsole = {
    log: console.log,
    info: console.info,
    warn: console.warn,
    error: console.error,
  }

  beforeEach(() => {
    // Mock console methods
    console.log = vi.fn()
    console.info = vi.fn()
    console.warn = vi.fn()
    console.error = vi.fn()
  })

  describe('configuration fallback', () => {
    it('should operate without Axiom environment variables', async () => {
      vi.stubEnv('AXIOM_TOKEN', '')
      vi.stubEnv('AXIOM_DATASET', '')

      try {
        const fallbackLogger = createLogger()

        await expect(fallbackLogger.info('Fallback message')).resolves.not.toThrow()
        await expect(fallbackLogger.flush()).resolves.not.toThrow()
        expect(console.warn).not.toHaveBeenCalled()
      } finally {
        vi.unstubAllEnvs()
      }
    })
  })

  afterEach(() => {
    // Restore original console methods
    console.log = originalConsole.log
    console.info = originalConsole.info
    console.warn = originalConsole.warn
    console.error = originalConsole.error
    vi.clearAllMocks()
  })

  describe('createCorrelationId', () => {
    it('should generate a valid UUID v4', () => {
      const correlationId = logger.createCorrelationId()

      // UUID v4 format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
      const uuidV4Regex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
      expect(correlationId).toMatch(uuidV4Regex)
    })

    it('should generate unique correlation IDs', () => {
      const id1 = logger.createCorrelationId()
      const id2 = logger.createCorrelationId()
      const id3 = logger.createCorrelationId()

      expect(id1).not.toBe(id2)
      expect(id2).not.toBe(id3)
      expect(id1).not.toBe(id3)
    })
  })

  describe('apiRequest', () => {
    it('should create request context with timing', () => {
      const ctx = logger.apiRequest('/api/users', 'GET', 'user123')

      expect(ctx).toHaveProperty('endpoint', '/api/users')
      expect(ctx).toHaveProperty('method', 'GET')
      expect(ctx).toHaveProperty('userId', 'user123')
      expect(ctx).toHaveProperty('correlationId')
      expect(ctx).toHaveProperty('startTime')
      expect(typeof ctx.startTime).toBe('number')
    })

    it('should normalize method to uppercase', () => {
      const ctx = logger.apiRequest('/api/posts', 'post', 'user456')
      expect(ctx.method).toBe('POST')
    })

    it('should generate correlation ID if not provided', () => {
      const ctx = logger.apiRequest('/api/data', 'GET')
      expect(ctx.correlationId).toBeDefined()
      expect(typeof ctx.correlationId).toBe('string')
    })

    it('should use provided correlation ID', () => {
      const customId = 'custom-correlation-id-123'
      const ctx = logger.apiRequest('/api/test', 'POST', undefined, customId)
      expect(ctx.correlationId).toBe(customId)
    })
  })

  describe('apiComplete', () => {
    it('should calculate request duration', async () => {
      const ctx = logger.apiRequest('/api/users', 'GET', 'user123')

      // Simulate some processing time
      await new Promise(resolve => setTimeout(resolve, 50))

      await logger.apiComplete(ctx, 200)

      // Verify console.info was called with duration
      expect(console.info).toHaveBeenCalled()
    })

    it('should warn on slow requests (>2000ms)', async () => {
      const ctx = logger.apiRequest('/api/slow', 'GET')
      // Mock a slow request by setting startTime in the past
      ctx.startTime = Date.now() - 2500

      await logger.apiComplete(ctx, 200)

      // Should have both info (completion) and warn (slow request) calls
      expect(console.info).toHaveBeenCalled()
      expect(console.warn).toHaveBeenCalled()
    })

    it('should not warn on fast requests (<2000ms)', async () => {
      const ctx = logger.apiRequest('/api/fast', 'GET')
      ctx.startTime = Date.now() - 100

      await logger.apiComplete(ctx, 200)

      expect(console.info).toHaveBeenCalled()
      expect(console.warn).not.toHaveBeenCalled()
    })
  })

  describe('apiResponse', () => {
    it('should create response context', () => {
      const ctx = logger.apiResponse('/api/posts', 200, 'user789')

      expect(ctx).toEqual({
        endpoint: '/api/posts',
        status: 200,
        userId: 'user789',
      })
    })

    it('should handle missing userId', () => {
      const ctx = logger.apiResponse('/api/public', 200)

      expect(ctx).toEqual({
        endpoint: '/api/public',
        status: 200,
        userId: undefined,
      })
    })
  })

  describe('log levels', () => {
    it('should log debug messages', async () => {
      await logger.debug('Debug message', { test: 'value' })
      expect(console.log).toHaveBeenCalled()
    })

    it('should log info messages', async () => {
      await logger.info('Info message', { test: 'value' })
      expect(console.info).toHaveBeenCalled()
    })

    it('should log warn messages', async () => {
      await logger.warn('Warning message', { test: 'value' })
      expect(console.warn).toHaveBeenCalled()
    })

    it('should log error messages', async () => {
      await logger.error('Error message', { test: 'value' })
      expect(console.error).toHaveBeenCalled()
    })
  })

  describe('context sanitization', () => {
    it('should redact sensitive fields in development', async () => {
      await logger.info('Test log', {
        userId: 'user123',
        token: 'secret-token',
        password: 'secret-password',
        customData: 'safe-value',
      })

      // In development, we can check the console output doesn't contain secrets
      expect(console.info).toHaveBeenCalled()
      const callArgs = (console.info as any).mock.calls[0]
      const logMessage = JSON.stringify(callArgs)

      expect(logMessage).not.toContain('secret-token')
      expect(logMessage).not.toContain('secret-password')
      expect(logMessage).toContain('[REDACTED]')
    })
  })

  describe('flush', () => {
    it('should complete without errors', async () => {
      await expect(logger.flush()).resolves.not.toThrow()
    })

    it('should be callable multiple times', async () => {
      await logger.flush()
      await logger.flush()
      await logger.flush()
      // Should not throw errors
    })
  })

  describe('error handling', () => {
    it('should handle errors gracefully in log methods', async () => {
      // Even if console throws (shouldn't happen, but for resilience)
      console.error = vi.fn(() => {
        throw new Error('Console error')
      })

      // Should not throw
      await expect(logger.error('Test error')).resolves.not.toThrow()
    })
  })

  describe('correlation ID workflow', () => {
    it('should support full request lifecycle tracking', async () => {
      // Generate correlation ID
      const correlationId = logger.createCorrelationId()

      // Start request
      const ctx = logger.apiRequest('/api/orders', 'POST', 'user999', correlationId)

      expect(ctx.correlationId).toBe(correlationId)
      expect(ctx.startTime).toBeGreaterThan(0)

      // Log during processing
      await logger.info('Processing order', { correlationId, orderId: 'order-123' })

      // Complete request
      await logger.apiComplete(ctx, 201)

      // Flush logs
      await logger.flush()

      // Verify all console calls happened
      expect(console.info).toHaveBeenCalledTimes(2) // info + apiComplete
    })
  })
})
